apiVersion: actions.github.com/v1alpha1
kind: AutoscalingRunnerSet
metadata:
  name: chris-pc-argocd-applications
  labels:
    app.kubernetes.io/version: "0.13.0"
spec:
  githubConfigSecret: github-config
  githubConfigUrl: https://github.com/chrismlee42/argocd-applications
  minRunners: 0
  template:
    spec:
      containers:
        - command:
            - /home/runner/run.sh
          image: ghcr.io/actions/actions-runner:latest
          name: runner
      restartPolicy: Never
      # serviceAccountName: chris-pc-argocd-applications-gha-rs-no-permission
